### ISSUE TITLE
动态库报错

### ISSUE THREAD

**Issue by Jacky-LinPeng** [pdcodeunder/cocoapods-ppbuild#1]
Podfile里面开启
`
# 动态库预编译
use_frameworks!
use_dynamic_binary!
`
pod insall之后

`
Multiple commands produce '/Users/mac/Library/Developer/Xcode/DerivedData/TestDemo-equwexjsbnpoxucpduojrnjyuldj/Build/Products/Debug-iphonesimulator/AFNetworking/AFNetworking.framework.dSYM':
1) That command depends on command in Target 'AFNetworking' (project 'Pods'): script phase “[CP] Copy dSYMs”
2) That command depends on command in Target 'AFNetworking' (project 'Pods'): script phase “[CP] Copy dSYMs”
3) That command depends on command in Target 'AFNetworking' (project 'Pods'): script phase “[CP] Copy dSYMs”
4) That command depends on command in Target 'AFNetworking' (project 'Pods'): script phase “[CP] Copy dSYMs”
5) That command depends on command in Target 'AFNetworking' (project 'Pods'): script phase “[CP] Copy dSYMs”
6) That command depends on command in Target 'AFNetworking' (project 'Pods'): script phase “[CP] Copy dSYMs”

`

**Comment by pdcodeunder** [comment]
暂时删除了动态库编译支持，已更新文档，后续再添加支持。动态库会拖慢app启动时间，建议使用静态库配置：
plugin 'cocoapods-ppbuild'
use_frameworks! :linkage => :static
use_static_binary!
